version: '3'

services:
#frontend client
  frontend-client:
    container_name: frontend
    image: 'demo-client'
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - docker-demo
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-api

#backend api
  backend-api:
    container_name : api
    image: demo-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
      - /api/node_modules
    networks:
      - docker-demo
    depends_on:
      - mongodb


#database
  mongodb:
    container_name : database
    image: mongo
    networks:
      - docker-demo
    ports:
      - 27017:27017
    restart: always
    volumes:
       - mongodb:/data/db


networks:
  docker-demo:
    driver: bridge

volumes:
  mongodb: