apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: demo-api
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: backend_container
        image: demo-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

