apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: demo-client
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      containers:
      - name: demo-client
        image: thisura97/demo-repo2:first
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
