apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: demo-client
  replicas: 5
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      containers:
      - name: frontend
        image: thisura97/demo-repo2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

